// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5Cop9JZJ5agbuMoMDOib3wyEWgh_v4Q',
    appId: '1:222818623791:web:f7da92ade9544d609941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    authDomain: 'labtest-e4b35.firebaseapp.com',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
    measurementId: 'G-H5MFG811WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtiJtcVyJ7zXh-vEcL_S0BObg1XGqWY-k',
    appId: '1:222818623791:android:55c71414f031cd389941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-rjYzjdGaNA3gbO3xyprY7-XI3wtx14',
    appId: '1:222818623791:ios:0c44ae0227e8e44d9941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd-rjYzjdGaNA3gbO3xyprY7-XI3wtx14',
    appId: '1:222818623791:ios:0c44ae0227e8e44d9941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX5Cop9JZJ5agbuMoMDOib3wyEWgh_v4Q',
    appId: '1:222818623791:web:75c43eb4519b42c39941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    authDomain: 'labtest-e4b35.firebaseapp.com',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
    measurementId: 'G-HY207PQL8R',
  );
}
