// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lB0jz-0cJOMJ2hmsVUx9DCnNKpsAQvI',
    appId: '1:350345097479:web:946a0232d8bbcfd1a755a2',
    messagingSenderId: '350345097479',
    projectId: 'bloodcollection-9117d',
    authDomain: 'bloodcollection-9117d.firebaseapp.com',
    databaseURL: 'https://bloodcollection-9117d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloodcollection-9117d.firebasestorage.app',
    measurementId: 'G-WW7YKK0N70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtiJtcVyJ7zXh-vEcL_S0BObg1XGqWY-k',
    appId: '1:222818623791:android:55c71414f031cd389941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-rjYzjdGaNA3gbO3xyprY7-XI3wtx14',
    appId: '1:222818623791:ios:0c44ae0227e8e44d9941da',
    messagingSenderId: '222818623791',
    projectId: 'labtest-e4b35',
    storageBucket: 'labtest-e4b35.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwsPBXw98Fh8h6gTK4jH0DDPs2KZf9TJo',
    appId: '1:350345097479:ios:4d6f0bf38f626976a755a2',
    messagingSenderId: '350345097479',
    projectId: 'bloodcollection-9117d',
    databaseURL: 'https://bloodcollection-9117d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloodcollection-9117d.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6lB0jz-0cJOMJ2hmsVUx9DCnNKpsAQvI',
    appId: '1:350345097479:web:acc02c5a2aa32772a755a2',
    messagingSenderId: '350345097479',
    projectId: 'bloodcollection-9117d',
    authDomain: 'bloodcollection-9117d.firebaseapp.com',
    databaseURL: 'https://bloodcollection-9117d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bloodcollection-9117d.firebasestorage.app',
    measurementId: 'G-FDH0TZSEHD',
  );

}