// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJizlnHduUPQvBj_x82jQWY8A9-vvhXU',
    appId: '1:1021212808125:web:76e6b1955f13dbfb67f8d4',
    messagingSenderId: '1021212808125',
    projectId: 'reels-b197b',
    authDomain: 'reels-b197b.firebaseapp.com',
    storageBucket: 'reels-b197b.firebasestorage.app',
    measurementId: 'G-6NKR2YGSSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnlTy4b6hDLmixJlCcHWtgZUEIwAIDbU',
    appId: '1:1021212808125:android:4aa967b427ccf74e67f8d4',
    messagingSenderId: '1021212808125',
    projectId: 'reels-b197b',
    storageBucket: 'reels-b197b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Xy7WW2YKq0rOW41kyQZ1E-hczEVzcjY',
    appId: '1:1021212808125:ios:a4188e62ffc468cb67f8d4',
    messagingSenderId: '1021212808125',
    projectId: 'reels-b197b',
    storageBucket: 'reels-b197b.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Xy7WW2YKq0rOW41kyQZ1E-hczEVzcjY',
    appId: '1:1021212808125:ios:a4188e62ffc468cb67f8d4',
    messagingSenderId: '1021212808125',
    projectId: 'reels-b197b',
    storageBucket: 'reels-b197b.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYJizlnHduUPQvBj_x82jQWY8A9-vvhXU',
    appId: '1:1021212808125:web:d21fad97acba79a667f8d4',
    messagingSenderId: '1021212808125',
    projectId: 'reels-b197b',
    authDomain: 'reels-b197b.firebaseapp.com',
    storageBucket: 'reels-b197b.firebasestorage.app',
    measurementId: 'G-LNKSHV43ZG',
  );
}
